#Configuracion de base de datos - Control Tardanzas
#Fri May 29 12:01:17 CEST 2026
db.host=localhost
db.nombre=control_tardanzas
db.password=
db.puerto=3306
db.url=jdbc\:mariadb\://localhost\:3306/control_tardanzas?useUnicode\=true&characterEncoding\=UTF-8&serverTimezone\=Europe/Madrid
db.user=root
